ARG CADDY_BUILDER_IMAGE_ALPINE=caddy:builder-alpine

FROM ${CADDY_BUILDER_IMAGE_ALPINE} AS builder

RUN caddy-builder \
    github.com/caddy-dns/cloudflare \
    github.com/WeidiDeng/caddy-cloudflare-ip

FROM caddy:alpine@sha256:3b2a0196e0687279c14c27adff9fc6b44acfa318dbb97eaebe385bdf99e5364c

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
