ARG CADDY_BUILDER_IMAGE_ALPINE=caddy:builder-alpine

FROM ${CADDY_BUILDER_IMAGE_ALPINE} AS builder

RUN caddy-builder \
    github.com/caddy-dns/cloudflare \
    github.com/WeidiDeng/caddy-cloudflare-ip

FROM caddy:alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
