ARG CADDY_BUILDER_IMAGE_ALPINE=caddy:builder-alpine

FROM ${CADDY_BUILDER_IMAGE_ALPINE} AS builder

RUN caddy-builder \
    github.com/caddy-dns/cloudflare \
    github.com/WeidiDeng/caddy-cloudflare-ip

FROM caddy:alpine@sha256:24d58e24e4231c6667677a39469a3d843a3222eadbf640f22933f24bed0939ec

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
